# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04019a10ca4e9270e76120896d285ee07537d1ed945afe247301b7fad0e1bced156d7a49079336d84940db546f42a00d5ba08509e83901537cb374e3b5eca91f

test:
  secret_key_base: cdce1f2c33fabaab2e2e39162cfc3312d1cc0cc49d86740ac057d7d2f895749cbe13348bece98b8a9a46de69e1309de09a05b988a5a0778afec1e10900007555

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
